---
title: "Portfolio Returns"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
# Shiny
library(flexdashboard)
library(shiny)
library(DT)

# Core
library(tidyverse)
library(tidyquant)

# Scripts
source("../00_scripts/convert_prices_to_returns.R")
```


User Input {.sidebar}
-----------------------------------------------------------------------

```{r}
fluidRow(
    column(6, textInput("stock1", "Stock 1", "SPY")),
    column(5, numericInput("w1", "Portf. %", 25, min = 1, max = 100))
)

fluidRow(
    column(6, textInput("stock2", "Stock 2", "EFA")),
    column(5, numericInput("w2", "Portf. %", 25, min = 1, max = 100))
)

fluidRow(
    column(6, textInput("stock3", "Stock 3", "IJS")),
    column(5, numericInput("w3", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
    column(6, textInput("stock4", "Stock 4", "EEM")),
    column(5, numericInput("w4", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
    column(6, textInput("stock5", "Stock 5", "AGG")),
    column(5, numericInput("w5", "Portf. %", 10, min = 1, max = 100))
)

# Select data

fluidRow(
    column(7, dateInput("date", "Starting Date", "2013-01-01", format = "yyyy-mm-dd"))
)

# Select rebalance interval

fluidRow(
    column(6, selectInput("rebalance", "rebal freq", 
                         c("Yearly" = "years", "Monthly" = "months", "Weekly" = "weeks")))
)


actionButton("go", "Submit")

```


Column {.tabset .tabset-fade}
-----------------------------------------------------------------------


```{r}
# event reactive filter

portfolio_returns_tbl <- eventReactive(input$go, {
    
    ## 1 Import stock prices ----
    
    symbols <- c(input$stock1, input$stock2,
                 input$stock3, input$stock4, input$stock5)
    
    prices <- tq_get(x = symbols,
                     get = "stock.prices",
                     from = "2012-12-31",
                     to = "2017-12-31") %>%
    
        select(date, asset = symbol, prices = adjusted)
    
    ## 2 Convert prices to returns
    
    asset_returns_long_tbl <- convert_prices_to_returns(prices, period_returns = "monthly")
    
    
    ## 3 Build a portfolio ----

    w <- c(input$w1 / 100,
           input$w2 / 100,
           input$w3 / 100,
           input$w4 / 100,
           input$w5 / 100)
    
    w_tbl <- tibble(symbols, w)
    
    
    portfolio_returns_tbl <- asset_returns_long_tbl %>%
    
        tq_portfolio(assets_col   = asset,
                     returns_col  = returns,
                     weights      = w_tbl,
                     col_rename   = "returns",
                     rebalance_on = input$rebalance)
    
})

# renderPrint(portfolio_returns_tbl())
```




### Histogram

```{r}
output$histogram <- renderPlot({
    
    portfolio_returns_tbl() %>%

    ggplot(aes(returns)) +
    geom_histogram(fill = "cornflower blue",
                   binwidth = 0.005) +

    labs(title = "Portfolio Returns Distribution",
         y = "count",
         x = "returns")
    
})

plotOutput(outputId = "histogram")

```

### Density

```{r}

output$density <- renderPlot({
    
    portfolio_returns_tbl() %>%

    ggplot(aes(returns)) +
    geom_density(aes(returns)) +

    labs(title = "Portfolio Returns Distribution",
         y = "distribution",
         x = "monthly returns")
    
})

plotOutput(outputId = "density")
```


### Histogram-Density

```{r}

output$histogram_density <- renderPlot({
    
    portfolio_returns_tbl() %>%

    ggplot(aes(returns)) +
    geom_histogram(fill = "cornflower blue",
                   binwidth = 0.01) +
    geom_density(aes(returns)) +

    labs(title = "Portfolio Histogram and Density",
         y = "distribution",
         x = "monthly returns")
    
})

plotOutput(outputId = "histogram_density")
```



