---
title: "Capital Asset Pricing Model"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
# Shiny
library(shiny)
library(flexdashboard)

# Core
library(tidyverse)
library(tidyquant)

# Interactive visualization
library(plotly)

# Script
source("../00_scripts/convert_prices_to_returns.R")
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
fluidRow(
    column(6, textInput("stock1", "Stock 1", "SPY")),
    column(5, numericInput("w1", "Portf. %", 25, min = 1, max = 100))
)

fluidRow(
    column(6, textInput("stock2", "Stock 2", "EFA")),
    column(5, numericInput("w2", "Portf. %", 25, min = 1, max = 100))
)

fluidRow(
    column(6, textInput("stock3", "Stock 3", "IJS")),
    column(5, numericInput("w3", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
    column(6, textInput("stock4", "Stock 4", "EEM")),
    column(5, numericInput("w4", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
    column(6, textInput("stock5", "Stock 5", "AGG")),
    column(5, numericInput("w5", "Portf. %", 10, min = 1, max = 100))
)

fluidRow(
    column(7, dateInput("date", "Starting Date", "2013-01-01", format = "yyyy-mm-dd"))
)

actionButton("go", "Submit")
```

Row {data-height=750}
-----------------------------------------------------------------------

```{r}
# portfolio returns

portfolio_returns_tbl <- eventReactive(input$go, {
    
    # Import prices
    symbols <- c(input$stock1, input$stock2,
                 input$stock3, input$stock4, input$stock5)
    
    prices <- tq_get(symbols,
                     get = "stock.prices",
                     from = input$date) %>%
        
        select(date, asset = symbol, prices = adjusted)
    
    # Convert prices to returns
    asset_returns_long_tbl <- prices %>% convert_prices_to_returns(period_returns = "monthly")
    
    # Combine individual returns into portfolio
    validate(need(input$w1+input$w2+input$w3+input$w4+input$w5 == 100,
                  "The portfolio weights must sum to 100%!"))
    
    w <- c(input$w1 / 100,
           input$w2 / 100,
           input$w3 / 100,
           input$w4 / 100,
           input$w5 / 100)
    w_tbl <- tibble(symbols, w)
    
    portfolio_returns_tbl <- asset_returns_long_tbl %>%
        
        tq_portfolio(assets_col = asset,
                     returns_col = returns,
                     weights = w_tbl,
                     col_rename = "returns",
                     rebalance_on = "months")
    
})

# renderTable(portfolio_returns_tbl())
```



```{r}
# 2 CAPM and market returns ----

portfolio_market_returns_tbl <- eventReactive(input$go, {
    
    # Get market returns
    market_returns_tbl <- tq_get("SPY",
                                 get = "stock.price",
                                 from = input$date) %>%
        select(date, asset = symbol, prices = adjusted) %>%
    
        # Convert prices to returns
        convert_prices_to_returns(period_returns = "monthly")
    
    # Combine market returns with portfolio returns
    portfolio_market_returns_tbl <- portfolio_returns_tbl() %>%
    
        # Add market returns
        mutate(market_returns = market_returns_tbl %>% pull(returns))
    
})



```


### Visualization

```{r}
renderPlotly({
    
    g <- portfolio_market_returns_tbl() %>%
        
        mutate(label = str_glue("portfolio return: {returns %>% scales::percent(accuracy = 0.01)}
                                market returns: {market_returns %>% scales::percent(accuracy = 0.01)}
                                date: {date}")) %>%

        ggplot(aes(market_returns, returns)) +
        geom_point(color = "cornflowerblue",
                   aes(text = label)) +
    
        labs(x = "market returns (S&P500)",
             y = "portfolio returns") +
    
        geom_smooth(method = "lm", se = FALSE,
                    size = 1.5, color = tidyquant::palette_light()[3])
    
    ggplotly(g, tooltip = "text")
    
})

```

Row {data-height=250}
-----------------------------------------------------------------------

### Model Results using S&P500 as the Market

```{r}
renderTable({
    
    portfolio_market_returns_tbl() %>%
    
        lm(returns ~ market_returns, data = .) %>%
        broom::tidy() %>%
        mutate(term = c("alpha", "beta"))
    
}, digits = 4)


```


